# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Use the quay.io/qm-images/ros2:rolling base image
FROM quay.io/qm-images/ros2:rolling

# Set environment variables
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV ROS_DISTRO=rolling

# Install additional dependencies (adjust as needed)
RUN dnf update -y && \
    dnf install -y \
    python3-pip \
    && dnf clean all

RUN pip3 install -U colcon-common-extensions

COPY ./src/engine/engine /ros2_ws/src

# Set up the ROS2 workspace
WORKDIR /ros2_ws
RUN echo "source /opt/ros2/install/setup.bash" >> ~/.bashrc
RUN . /opt/ros2/install/setup.bash && colcon build
